USE [master]
GO

/****** Object:  Database [TradingGmbH]    Script Date: 24.02.2023 14:14:32 ******/
CREATE DATABASE [TradingGmbH]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TradingGmbH', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TradingGmbH.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TradingGmbH_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TradingGmbH_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TradingGmbH].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TradingGmbH] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TradingGmbH] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TradingGmbH] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TradingGmbH] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TradingGmbH] SET ARITHABORT OFF 
GO

ALTER DATABASE [TradingGmbH] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TradingGmbH] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TradingGmbH] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TradingGmbH] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TradingGmbH] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TradingGmbH] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TradingGmbH] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TradingGmbH] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TradingGmbH] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TradingGmbH] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TradingGmbH] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TradingGmbH] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TradingGmbH] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TradingGmbH] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TradingGmbH] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TradingGmbH] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TradingGmbH] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TradingGmbH] SET RECOVERY FULL 
GO

ALTER DATABASE [TradingGmbH] SET  MULTI_USER 
GO

ALTER DATABASE [TradingGmbH] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TradingGmbH] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TradingGmbH] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TradingGmbH] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TradingGmbH] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TradingGmbH] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TradingGmbH] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TradingGmbH] SET  READ_WRITE 
GO


